language: node_js
node_js: node
script:
- npm test
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 1RspBT4qhUndPfMiaauCo16iu9X7Xc/InKT+S5ETvnKEzCfXl+nKHWB/ZIQHl2f+iHrNebfs5kaNiTDWYVXxYmYSzYiVOup/g723KL2IJkgOAec5vs7Szr1dDEZz2jKpHFILJbpIqvJ2bNsj+/OePxeZoaFPUSJQTXV7lb3nSrnoEtt5Er2yGqN72EZ0JNH5kqCeuS4jtfCVkK/Rem9kV0y8tPZYWDdovcZOR5zFdVe0rP1D9GX5GcFv/Uw6rjKGvPb88CUOyyVujXmvgWwhwUb6Ul6EAxuhv/Wl40D5GhpaggofpOHs6peKNu2rUk7yOjX3dPz/vB16IeB9kmvsa/gVFFJ5E8Ykzm7OvEyW9si1Rby61QDuczaqukNN4mkSNXuCAhUMB4sG/0tARBm7+vkOPhQqItpPt9AZaoYravAXtOydkBL1pPZ90bYP5PFr1knM3B/jr93AxXC4qjjhp3jaDS/pCvCpH+XePMPhW0e8kyFwPM8eYd4DSiZ17SRbRdjOqEVDbB2Gww8bq7OybZghHGZrSvbM5fDV3NldYem6BlVXX6eBv4qba+dI5Oeb5xrLJ+fEXI+H3D4b6WycYcZ109ocJER8w0hb/isR0NLNrB1kEIoOakMdRcLwUmbEw723Lz2E234aBhpc404OeOWl+/aWk/AYRJvY9BG6SrU=
  app: expat-life
  on:
    repo: RyanOkamuro/expat-life
