language: node_js
node_js: node
script:
- npm test
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: STRLYuvVPu8ingV0fLGQ0I2l/5o9ePvZOfo6XpO1FGDH3vQnhMCzRRQFjA7P8SKbIkhISaPGoYezFZnF6iTVn/IiVN9G0Nooj2UpkalAR4auelQH3Ki+12vFL/WpdM1aWktfuso6SmRq+BAxDegJkuQZAa1ofARIZqisn3IXXEa4BOVoWEwFENJKeNOBVGRsPokqguxmNTYnudcaCpgJ6m/LdInVMhlGppCQICAnXlQaoWBen9Z0goViQR/iZdngXDL+psTIjpqCUV8JElIITIf3pggtDNFEpxFj4t3IdsyCl21dhzNXbXAgN1+1YJhv4Aa+jVkRSkZQOpUQO3dblfOO8Ki+sg8/eDOEl3z66pwc+z4GRh7eb17dMiYSfxCJaY6fQDbPhnEu4thXTyhT/ifJ0d3mb/H4yTMqGOCE56F+jPpTGfS71jITkz5GThAF+1i2HCjxOZegcekoFiOVLSfoaLQCqyh7CoM0LNW0uAiZmoQ4EZxXj5uXHp1ehn78+g6XKcUu7FJRqWw8vhTfvoYO3mYhc24lLApfoxFt2UJRfstletQNtNhUawcAaKUqhiNqdqF+34QHNKN4cySXV2e7IUkTF6qNvX6yq4TIPSmM7zJS/Y/rLv1UqvM9ikj0w6syURcNTDmc18mGfms3RsFIOP4tu16hKQoK3Oete90=
  app: expat-life
  on:
    repo: RyanOkamuro/expat-life
