language: node_js
node_js: node
script:
- npm test
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: lFmkGxlo5tStPjEp1onkAR16mpsMKWDMT5Ntowr8KvfxnrUTTY13DYpRnLLjDF7zQMulWlTg/nDF982I8nL2ksoIDy/e7cb6qrRdarYK3p4FqXFRQKIi9b9QtyFVmNrAsREn4vVzPGlkkXGy2kFgtiBp46nzw3GR4pyIsXhGQdsMV/ags3eagWuh6H2WH1P5eHAezuRVgSq9AqFlp5zMn0fXULj/2ZdH75eelEG6O57Nu3aHdcCK5moIWzdgCstcjOWuaIeq8QvALJ9Zs8ZzlftO4NF2+KP3AGXUwze8Qus+sdjsgwMw/wVRsquEMOlkb60EPOb0g0DcY5QqqUyK4tX9ZkBN6a7brmnATMhtTY/VuN+vlESRRt9l64EcT5cLpvhhZELv4E9DZ76P3iWJKyPi5L7JfpbsF35BbX3RjO0s1elYGURXghkURwpNvudDi3b0teUllyIpomGFsERe5M2LfUSGuiiHd6cqd8OTw53+I8d4CdA1FAe4pmHVk7pAWU9AAmwJBV7O8X6EwxSW26/gppxs7CSWV02/al741AXsg5WPjs/N+j8xUp23TX/11+E7hBSF3aK8mwm+Y7Y7R+vwsydT8IQyjlBBhruwBx7zSj3g2eG0A7tC3D2IFg9TxLOfXJXC6PGTwFryGqVnMAFb6hwlUP5/RpwX+LoUXu0=
  app: expat-life
  on:
    repo: RyanOkamuro/expat-life
